### ISSUE TITLE
Possible to run without Horovod ?

### ISSUE THREAD

**Issue by NoRealLogin** [TRI-ML/KP2D#22]
Hello,

I wanted to know if there was a solution to by-pass Horovod which is hard (impossible?) to install on windows yet.
Is there any obligatory functions from Horovod used in the scripts that I can't find anywhere else ?
I only work with 1 GPU.

Best regards.

**Comment by RaresAmbrus** [comment]
Hi, I think you should be able to run without Horovod with minimal changes. We call hvd_init() [here](https://github.com/TRI-ML/KP2D/blob/master/scripts/train_keypoint_net.py#L67), which runs the functions from [horovod.py](https://github.com/TRI-ML/KP2D/blob/master/kp2d/utils/horovod.py), where we check of Horovod is available. I think the main change you will have to do is replace the Horovod optimizer [here](https://github.com/TRI-ML/KP2D/blob/master/scripts/train_keypoint_net.py#L95) with the Pytorch optimizer (we should actually be checking if Horovod is available there anyway ...). Since you'll be running single GPU, you can get rid of the allreduce operations [here](https://github.com/TRI-ML/KP2D/blob/master/scripts/train_keypoint_net.py#L219), plus replace `hvd.rank()` and `hvd.size()` with `rank()` and `world_size()` from [horovod.py](https://github.com/TRI-ML/KP2D/blob/master/kp2d/utils/horovod.py). 

Let me know how it goes!

**Comment by NoRealLogin** [comment]
It works great, I've been able to replace the hvd.functions and start the training on coco's dataset.
But since I work on private training and validation sets I've had other issues I'll may post in another topic. 

Thanks for your reply !
