### ISSUE TITLE
About the code

### ISSUE THREAD

**Issue by mamba-wang** [TRI-ML/KP2D#7]
Thanks for your work. 
I have a question about the code. In file "augmentation.py", the source image is the original input image, and the target image (image_aug) is warpped from source image using H matrix. But, in file "KeypointNetwithIOLoss.py",  the augmented image (image_aug) is used as the source image, why?
I am really confused by this, could you help me with this question? Thanks a lot!

**Comment by RaresAmbrus** [comment]
Hi, thanks for the question! Technically we can use the term source and target interchangeably, as they are both passed through the keypoint net [here](https://github.com/TRI-ML/KP2D/blob/master/kp2d/models/KeypointNetwithIOLoss.py#L246). What's important is that we use the correct homography [here](https://github.com/TRI-ML/KP2D/blob/master/kp2d/models/KeypointNetwithIOLoss.py#L262). In our case, because of the way we construct the target image in [augmentation.py](https://github.com/TRI-ML/KP2D/blob/6c6f52c76cafab36f189820c90c03b2cd1fb9db2/kp2d/datasets/augmentations.py#L343-L344) by using the grid sampling operation, the homography warps target pixels into the source image, and we use it correctly in the KeypointNetWithIOLoss. 

But you're right that the terminology is confusing, we should be consistent with how we use `source` and `target` everywhere in the code, I'll make a note to fix that. I hope that helps and thanks for spotting this!

**Comment by mamba-wang** [comment]
Thank you very much!

**Comment by RaresAmbrus** [comment]
We just merged a [PR](https://github.com/TRI-ML/KP2D/commit/4d1556702cc28bf2791749c8fdcdbec891c3093d) with the cleanup - hopefully it makes more sense now!
